import { Poppins,Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const poppins = Poppins({ subsets: ["latin"] ,
weight: '400',},);
const playfair = Playfair_Display({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white">
      <body className={playfair.className}  >
       
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
